version: 2

# ──────────────── Groups  ──────────────────────────────────────────
x-schedule-weekly-friday: &schedule_weekly_friday
  interval: "weekly"
  day: "friday"

x-reviewers-maintainers: &reviewers_maintainers
  reviewers:
    - "@maintainers"
# ───────────────────────────────────────────────────────────────────


updates:

  ###################################################################
  # GitHub Actions – keeps our workflow actions up-to-date
  ###################################################################
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: *schedule_weekly_friday
    target-branch: "dev"
    <<: *reviewers_maintainers


  ###################################################################
  # Docker
  ###################################################################
  - package-ecosystem: "docker"
    directory: "/"
    schedule: *schedule_weekly_friday
    target-branch: "dev"
    <<: *reviewers_maintainers


  ###################################################################
  # Python / pip
  ###################################################################
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 5     # prevent a flood of minor bumps
    groups:                         # bundle low-impact libs together
      low-priority:
        patterns:
          - "pytest-*"
          - "black"
    schedule: *schedule_weekly_friday
    target-branch: "dev"
    <<: *reviewers_maintainers
