###############################################################################
# UNIVERSAL CI WORKFLOW
# • Runs on every push to master and on every pull-request.
# • Starts with a read-only GITHUB_TOKEN (least-privilege).
# • Auto-detects Node, Java (Gradle or Maven), Go, or Python projects.
###############################################################################

name: CI (auto-detect & test)

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read          # prevents a compromised action from pushing or tagging

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test (any language)

    steps:
      # 1️⃣  Always check out repo
      - name: Checkout sources
        uses: actions/checkout@v4

      #######################################################################
      # 2️⃣  Language-specific tool-chains (each wrapped in an `if:` filter)
      #######################################################################

      # ── Node / npm ───────────────────────────────────────────────────────
      - name: Set up Node
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # ── Java (Gradle OR Maven) ──────────────────────────────────────────
      - name: Set up Java
        if: ${{ hashFiles('**/build.gradle') != '' || hashFiles('**/pom.xml') != '' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # ── Go ──────────────────────────────────────────────────────────────
      - name: Set up Go
        if: ${{ hashFiles('go.mod') != '' }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # ── Python ──────────────────────────────────────────────────────────
      - name: Set up Python
        if: >-
          ${{
            hashFiles('requirements.txt')   != '' ||
            hashFiles('pyproject.toml')     != '' ||
            hashFiles('setup.py')           != ''
          }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      #######################################################################
      # 3️⃣  Install dependencies & run tests  (one step per language)
      #######################################################################

      - name: Node – install & test
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          npm ci
          npm test

      - name: Gradle – test
        if: ${{ hashFiles('**/build.gradle') != '' }}
        run: ./gradlew test --no-daemon

      - name: Maven – test
        if: ${{ hashFiles('**/pom.xml') != '' }}
        run: mvn --batch-mode -ntp test

      - name: Go – test
        if: ${{ hashFiles('go.mod') != '' }}
        run: go test ./...

      - name: Python – install & test
        if: >-
          ${{
            hashFiles('requirements.txt')   != '' ||
            hashFiles('pyproject.toml')     != '' ||
            hashFiles('setup.py')           != ''
          }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ];  then pip install .; fi
          pytest -q || true                    # green if no tests yet

      #######################################################################
      # 4️⃣  Shell-script lint (runs regardless of language)
      #######################################################################
      - name: Lint shell scripts
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck $(git ls-files '*.sh') || true
